Depext: fix alpine tagged repositories handling
ocaml/opam pull request #4758
Opened 2021-07-21 17:40 UTC by rjbou

Some examples of the new behavior
```
libx11-dev policy:
 1.7.1-r0:
   lib/apk/db/installed
   https://dl-cdn.alpinelinux.org/alpine/v3.13/main
 1.7.2-r0:
   @edge https://dl-cdn.alpinelinux.org/alpine/edge/main
```
* `libx11` as installed
* `libx11@edge` as available
```
bubblewrap policy:
 0.4.1-r2:
   lib/apk/db/installed
   https://dl-cdn.alpinelinux.org/alpine/v3.13/main
   @edge https://dl-cdn.alpinelinux.org/alpine/v3.13/main
   https://dl-cdn.alpinelinux.org/alpine/edge/main
   @edge https://dl-cdn.alpinelinux.org/alpine/edge/main
```
* `bubblewrap` as installed
* `bubblewrap@edge` as available
```
capnproto policy:
  0.8.0-r1:
    @edgecommunity https://dl-cdn.alpinelinux.org/alpine/edge/community
```
* `capnproto-dev@edgecommunity` as available

2021-07-21 17:47 UTC, kit-ty-kate commented
> `bubblewrap@edge` as available

I don't think this should be the behaviour in this case. For example:
```
bash-5.1$ apk policy gmp-dev
gmp-dev policy:
  6.2.1-r0:
    https://dl-cdn.alpinelinux.org/alpine/v3.13/main
    @edge https://dl-cdn.alpinelinux.org/alpine/v3.13/main
    https://dl-cdn.alpinelinux.org/alpine/edge/main
    @edge https://dl-cdn.alpinelinux.org/alpine/edge/main
bash-5.1$ sudo apk add gmp-dev@edge
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
(1/2) Installing libgmpxx (6.2.1-r0)
(2/2) Installing gmp-dev (6.2.1-r0)
OK: 228 MiB in 80 packages
bash-5.1$ apk policy gmp-dev
gmp-dev policy:
  6.2.1-r0:
    lib/apk/db/installed
    https://dl-cdn.alpinelinux.org/alpine/v3.13/main
    @edge https://dl-cdn.alpinelinux.org/alpine/v3.13/main
    https://dl-cdn.alpinelinux.org/alpine/edge/main
    @edge https://dl-cdn.alpinelinux.org/alpine/edge/main
```
Both should be marked as installed if they have the same version number

2021-07-21 17:54 UTC, rjbou commented
Oh, I made a mistake in the example. In the code the `installed` state is [reverted](https://github.com/ocaml/opam/pull/4758/files#diff-6c0a6590c49c5a229f469d627b9e9484f1b20c1fb5fb1c8102d64a3d2c1d09b6R266-R273) only if there is another version field, not another repo line. I'll update the main comment

2021-07-21 19:56 UTC, kit-ty-kate reviewed
Some minor changes to simplify and harden the codebase, but overall it looks ok.
I haven't tested it yet, I'll do that tomorrow.

2021-07-21 19:56 UTC, kit-ty-kate commented on src/state/opamSysInteract.ml
> +              pkg, installed, instavail)
```suggestion
              let repo = Re.Group.get_opt (Re.exec repo_name l) 1 in
              let instavail = add_pkg pkg ~repo installed instavail in
              pkg, installed, instavail)
```

2021-07-21 19:56 UTC, kit-ty-kate commented on src/state/opamSysInteract.ml
>                let grs = Re.exec repo_name l in
```suggestion
```

2021-07-21 19:56 UTC, kit-ty-kate commented on src/state/opamSysInteract.ml
> +      let add_pkg pkg ?repo installed (inst,avail) =
```suggestion
      let add_pkg pkg ~repo installed (inst,avail) =
```

2021-07-21 19:56 UTC, kit-ty-kate commented on src/state/opamSysInteract.ml
> +            try (* tagged repo *)
```suggestion
            (* repo (tagged and non-tagged) *)
```

2021-07-21 19:56 UTC, kit-ty-kate commented on src/state/opamSysInteract.ml
> +            else if Re.execp is_installed l then
I can't add a suggestion on unchanged code above but the definition for `is_installed` could be a bit more precise.
Currently, according to the code source:
- https://git.alpinelinux.org/apk-tools/tree/src/app_policy.c
- https://git.alpinelinux.org/apk-tools/tree/src/database.c#n58
Only `lib/apk/db/installed` is possible there to let the user know the package is installed, and anything else (including something like `https://dl-cdn.alpinelinux.org/alpine/v3.13/installed`) is possible to list a repository.

2021-07-22 10:12 UTC, kit-ty-kate requested changes

2021-07-22 10:12 UTC, kit-ty-kate commented on src/state/opamSysInteract.ml
> +                OpamStd.String.ends_with ~suffix:"(installed):" l
According to https://git.alpinelinux.org/apk-tools/tree/src/app_policy.c and local testing this is never the case. Their own example is wrong and probably just an approximation

2021-07-22 14:36 UTC, kit-ty-kate approved these changes
Tested successfully

2021-07-22 14:37 UTC, merged