Make archive-mirrors modifiable via opam config
ocaml/opam pull request #5321
Opened 2022-10-18 21:23 UTC by hannesm

fixes #5316

2022-10-19 18:19 UTC, rjbou requested changes

2022-10-19 18:19 UTC, rjbou commented on src/client/opamConfigCommand.ml
> +        "archive-mirrors", Atomic,
This field is a list of urls, it should be `Modifiable` (appending urls) not `Atomic` (replacement)

2022-10-19 18:25 UTC, rjbou approved these changes
Updated to make it an extendable field + add some test

2022-10-20 23:16 UTC, hannesm commented
thanks :)

2022-10-21 11:04 UTC, kit-ty-kate commented
Thanks!

2022-10-21 11:04 UTC, merged