Display an appropriate error message when the file given to opam init --config does not exist
ocaml/opam pull request #5979
Opened 2024-05-28 21:29 UTC by kit-ty-kate

Fixes #5971 

This PR introduces `OpamUrl.kind` which i think is an improvement over `OpamUrl.local_{file,dir}` as way of detecting if a url is local or not. Most functions that use `OpamUrl.local_{file,dir}` already check later if the file exist and fail gracefully so there is no need to check twice.

I opened https://github.com/ocaml/opam/issues/5978 to think about removing `local_{file,dir}` in the future, but for now this would be a fairly intrusive change.

2025-04-14 13:38 UTC, rjbou requested changes
Discussed in dev meeting, it needs more design. At current stage, it is not possible to have a local path that is a vsc.
I've added some `opam init --config` tests

2025-10-02 12:24 UTC, kit-ty-kate commented on src/core/opamUrl.ml
> +    | Some _, {backend = `rsync; _} -> LocalPath
no because there is no guarantee that the files are in the state that you want on disk (it could point to a different branch, be a bare git repo and thus have no files checked-out, …)

2025-10-02 12:25 UTC, kit-ty-kate commented on src/repository/opamDownload.ml
> +    OpamConsole.error_and_exit `Internal_error
i strongly think this should be an error

2025-10-02 12:26 UTC, kit-ty-kate commented on src/repository/opamDownload.ml
> +    OpamConsole.error_and_exit `Internal_error
That's outside of the scope of this PR

2025-11-21 17:18 UTC, rjbou reviewed
The purpose of the PR and the general way to do it looks good to me.
However, i have several comments.
On the main topic of this PR:
* should we require that all config files are good, or should we skip the ones that are not compliant (bc not found, or backend, or even parsing failures). Currently, parsing errors are erroring at the first failure (related to comment XXX)
* at the moment, parsing failure are reported as is. Do we want to handle more gracefully that in that PR ? 
```
$ opam init --config /tmp/parse-error
Configuring from /tmp/parse-error and then from built-in defaults.
[ERROR] Error in configuration file, fix it, use '--no-opamrc', or check your '--config FILE' arguments:
At /tmp/t:1:136-1:137::
Parse error
```

On the addition of the type `OpamUrl.kind`.
> I opened #5978 to think about removing local_{file,dir} in the future, but for now this would be a fairly intrusive change.

I don't agree. I had to make those changes to be able to precise what are the needs of the type (https://github.com/ocaml/opam/pull/5979#discussion_r2547135194) and confirm the intuition i had.
Having a first PR that adds this type and use it through the codebase without `local_file` and `local_dir` will permit us to refine its definition and usage. Then, we'll be able to use it directly in this PR.
I have a dirty/draft local branch with it, and what i saw is having this type helps to have a more fine grained control (checks) and information (when reading code) about what we expect from those files/directories.

2025-11-21 17:18 UTC, rjbou commented on src/repository/opamDownload.ml
> +    OpamConsole.error_and_exit `Internal_error
Even if it is outside the scope, it is something that we could discuss, at least to see if it worth opening an issue

2025-11-21 17:18 UTC, rjbou commented on src/core/opamUrl.ml
> +    | Some _, {backend = `rsync; _} -> LocalPath
For several functions, we need to have a local path that is a version control. Sometimes we just need to check if it is a local vcs-ed path, sometimes just local path, sometimes local path non vcs-ed.

2025-11-21 17:18 UTC, rjbou commented on src/repository/opamDownload.ml
> +  match OpamUrl.kind url with
This change is not a change related to the PR purpose

2025-11-21 17:18 UTC, rjbou commented on src/client/opamCommands.ml
> +            (OpamUrl.to_string url);
I think that we should go through the entire list and then fail gracefully with a complete error message. Here, if some have as argument `--config non-existent --config vcs-file --config ssh-file`, they'il need to run opam init 3 times to remove all errors.

2025-11-21 17:18 UTC, rjbou commented on src/client/opamCommands.ml
> +            (OpamUrl.to_string url);
At the moment, parsing failure are reported as is
```
$ opam init --config /tmp/parse-error
Configuring from /tmp/parse-error and then from built-in defaults.
[ERROR] Error in configuration file, fix it, use '--no-opamrc', or check your '--config FILE' arguments:
At /tmp/t:1:136-1:137::
Parse error
```
Do we want to handle more gracefully that in that PR ?

2025-11-21 17:18 UTC, rjbou commented on src/client/opamCommands.ml
> +            (OpamUrl.to_string url);
It is possible to factorise these cases
```suggestion
        | VersionControl _ | Ssh as kind ->
          OpamConsole.error_and_exit `Bad_arguments
            "%s url not supported for %S"
            (OpamUrl.string_of_kind kind)
            (OpamUrl.to_string url);
```

2025-11-21 17:18 UTC, rjbou commented on src/repository/opamDownload.ml
> +    OpamConsole.error_and_exit `Internal_error
I may have put my comment not in the good place, cf comment in XXX

2025-11-21 18:15 UTC, kit-ty-kate commented on src/client/opamCommands.ml
> +            (OpamUrl.to_string url);
I don't think this is worth spending the time to design this just to support such a niche corner-case

2025-11-21 18:18 UTC, kit-ty-kate commented on src/core/opamUrl.ml
> +    | Some _, {backend = `rsync; _} -> LocalPath
The problem with local VCS paths, is that there are no telling that a path to a file is the correct one. Given that we do not know the current branch of whatever is checked-out locally, or even if it is checked-out at all (e.g. bare git repositories)

2025-11-21 19:07 UTC, kit-ty-kate commented on src/repository/opamDownload.ml
> +  match OpamUrl.kind url with
Fair enough, i removed that commit

2025-11-21 19:22 UTC, kit-ty-kate commented
@rjbou i believe all your comments have been taken care of by ma last rebase and should be ready to merge. I've removed the `kind` type given it requires more discussion and this is tracked by https://github.com/ocaml/opam/issues/5978

2025-11-24 14:58 UTC, kit-ty-kate commented on tests/reftests/init.test
> +### opam init --bypass-checks --bare --no-setup --config http://som.e/url/to/config | sed-cmd curl | "${OPAMVERSION}" -> "current" | "[^ ]*build_[^ ]*\.part" -> file.part
```suggestion
### opam init --bypass-checks --bare --no-setup --config http://som.e/url/to/config | sed-cmd curl | "${OPAMVERSION}" -> "current" | "[^ ]*\.part" -> file.part
```

2025-11-25 16:24 UTC, rjbou commented on src/client/opamCommands.ml
> +            (OpamUrl.to_string url);
Fair enough. Opened #6814 to track it.

2025-11-25 16:59 UTC, rjbou commented on master_changes.md
> +  * Display an appropriate error message when the file given to `opam init --config` does not exist or is in a VCS [#5979 @kit-ty-kate - fix #5971]
```suggestion
  * ✘ Display an appropriate error message when the file given to `opam init --config` does not exist or is in a VCS. This changes the behaviour for VCS local urls that was previously retrieved. [#5979 @kit-ty-kate - fix #5971]
```

2025-11-25 17:01 UTC, rjbou approved these changes
I've updated the PR with some tests (several errors and parsing errors) and fixed their numbering, and removed a trailing `.` at the end of the non existent file message.
Apart the precision of behaviour change in changes, lgtm!

2025-11-25 19:00 UTC, kit-ty-kate commented
ocaml-benchmarks is hitting a 502 bad gateway so i'm guessing it won't start. Ignoring.

2025-11-25 19:00 UTC, merged