Avoid head -c GNUism in reftests
ocaml/opam pull request #5989
Opened 2024-06-04 19:19 UTC by madroach

`head -c` is not posix-compliant, use `cut -b` instead.

2024-06-04 19:22 UTC, kit-ty-kate approved these changes

2024-06-04 19:22 UTC, kit-ty-kate commented on master_changes.md
> +  * [BUG]: head -c is not posix compliant. Use cut -b instead.
```suggestion
  * [BUG]: head -c is not posix compliant. Use cut -b instead. [#5989 @madroach]
```

2024-06-06 09:26 UTC, rjbou approved these changes
thanks!

2024-06-06 09:28 UTC, rjbou requested changes
There is a missing one in list.unix.test

2024-06-06 21:42 UTC, madroach commented
> There is a missing one in list.unix.test

This one uses `head -n 1`, which is POSIX conforming. It's the `-c 1` parameter, which is not POSIX conforming.

2024-06-27 15:40 UTC, rjbou approved these changes

2024-07-02 12:27 UTC, kit-ty-kate commented
Thanks a lot!

2024-07-02 12:27 UTC, merged