Make it so pin list display the current revision of the pinned repo
ocaml/opam pull request #6274
Opened 2024-10-28 20:30 UTC by desumn

Implementation of issue #5533 

It works, but I'm not sure it's the best way to do it

2024-10-28 20:35 UTC, desumn commented
In particular, may the url or revision be empty for a git/hs/darcs kind?

2024-10-29 14:34 UTC, rjbou reviewed
Thank you for you PR!
You'll find some comments specific to the implementation the implementation.
To complete the PR, it needs also to:
* [x] add a test (we can do it)
* [ ] update the list manpage text to inform about the new column, especially that it is the hash of the current state of the source, not the installed one.
* [ ] polishing (remove trailing whitespace, indent, 80 columns), but we will do it at the end.

A todo for the dev team: we'll need to add a more exhaustive test to pin, existing one tests only the several kind of pin (vcs/path/version), but not the not synchronised package.

2024-10-29 14:34 UTC, rjbou commented on src/client/opamPinCommand.ml
> +        | "git" | "hg" | "darcs" ->
You can match on `OpamUrl.backend` here. Here is an example:
https://github.com/ocaml/opam/blob/8e3ee689a9cf34aa0c6203f8d948b2d20075d9e5/src/state/opamFileTools.ml#L394-L397

2024-10-29 14:34 UTC, rjbou commented on master_changes.md
> +  * [NEW] Make it so pin list display the current revision of a pinned repository [#6274 @desumn]
```suggestion
  * [NEW] Make it so pin list display the current revision of a pinned repository [#6274 @desumn - fix #5533]
```

2024-10-29 14:45 UTC, kit-ty-kate requested changes

2024-10-29 16:34 UTC, desumn commented on src/client/opamPinCommand.ml
> +          OpamPackage.Version.to_string rev
I agree

2024-10-29 16:39 UTC, desumn commented on src/client/opamPinCommand.ml
> +               (OpamFile.URL.url url) in
Yes, however I don't really know where to cache the result

2024-10-29 19:45 UTC, kit-ty-kate approved these changes
lgtm. Thanks for this contribution!
We'll do the rest (fix the tests)

2024-10-29 20:14 UTC, kit-ty-kate commented on src/client/opamPinCommand.ml
> +               (OpamFile.URL.url url) in
In view of https://github.com/ocaml/opam/pull/6278 and similar uses of `OpamRepository.revision` it sounds totally fine to not cache this. If we want it in the future we can do it separately.

2024-11-26 14:57 UTC, rjbou commented
Discussed on dev meeting: We end up converging to this syntax
![image](https://github.com/user-attachments/assets/fddb0c74-84e8-40e5-9deb-3709c404172a)

2024-11-27 15:31 UTC, kit-ty-kate commented on .github/scripts/main/main.sh
> +  if [ "$GITHUB_EVENT_NAME" = "pull_request" ] && git ls-remote --exit-code origin $GITHUB_PR_USER/$BRANCH ; then
```suggestion
  if [ "$GITHUB_EVENT_NAME" = "pull_request" ] && git ls-remote --exit-code origin "$GITHUB_PR_USER/$BRANCH" ; then
```

2024-11-27 17:06 UTC, rjbou approved these changes
Thanks!!

2024-11-27 17:06 UTC, merged